### ISSUE TITLE
Work out how the like count mechanism will work

### ISSUE THREAD

**Issue by pcnoic** [pcnoic/tynr#1]
### Overview

The functionality for liking a post is already there. We need a way to be able to count the amount of likes that a TYN receives, update the front-end and increase the counter in the database. 

### Tasks

-  [ ] find a nice interface element for counting likes 
-  [ ] figure out a way to store the count of likes in the database 
       - right now we have three identifiers in the javascript object that is a `tyn`. `content`, `liked`, `date`. The `id` is auto-   generated from Firestore. We probably need to add another identifier named likeCount, make it a number in the Firestore collection (collection is like a table) and increase it when someone new presses the button. 
- [ ] new visitors **should not have** a _tyn_ liked because someone else liked it. We need to **clear the like state** after each refresh or send out a `cookie` to track all likes  a visitor has made since **we don't have any user information.** 

### Acceptance Criteria

Be able to like a _tyn_, display the count of the likes in a _tyn_, increase the tyn like count only for separate users liking a _tyn_.

**Comment by pcnoic** [comment]
There is some work that needs to be done in the cookie section but we will track this in a separate issue. Closing...
