### ISSUE TITLE
Make the tyn search in the right drawer work

### ISSUE THREAD

**Issue by pcnoic** [pcnoic/tynr#7]
### Overview 

A user should have the ability to search over the tyns collections in the firestore database so that it can get a list of tyns that contain the word that he is searching for. The search is not case-sensitive and non-wrapping. For example: 

Bitch I'm a mother! - cofounder of TYN.FM 

User searches for "i'm". The search should return the tyn. 

### Tasks 

- [x] figure out how to search over a firestore collection. There's probably a code snippet in the firestore documentation. 
- [x] implement the searching feature in the search input form in the right drawer.
- [x] update the `tyns` array in the home page so that it only contains the list that is returned from the search. 

### Acceptance Criteria 

Have a working search form for tyns based on their `content` element.
